export const testData = [
    {
      "id": 1,
      "DESCRIPTION": "Creative Development - 3 x 30 sec Video & Photography",
      "UNITS": 5,
      "UNIT_PRICE": 50,
      "AMOUNT_AED": 500,
    },
    {
      "id": 2,
      "DESCRIPTION": "Creative Development - 3 x 30 sec Video & Photography",
      "UNITS": 5,
      "UNIT_PRICE": 50,
      "AMOUNT_AED": 500,
    },
    {
      "id": 3,
      "DESCRIPTION": "Creative Development - 3 x 30 sec Video & Photography",
      "UNITS": 5,
      "UNIT_PRICE": 50,
      "AMOUNT_AED": 500,
    },
    {
      "id": 4,
      "DESCRIPTION": "Creative Development - 3 x 30 sec Video & Photography",
      "UNITS": 5,
      "UNIT_PRICE": 50,
      "AMOUNT_AED": 500,
    },
    {
      "id": 5,
      "DESCRIPTION": "Creative Development - 3 x 30 sec Video & Photography",
      "UNITS": 5,
      "UNIT_PRICE": 50,
      "AMOUNT_AED": 500,
    },
    {
      "id": 6,
      "DESCRIPTION": "Creative Development - 3 x 30 sec Video & Photography",
      "UNITS": 5,
      "UNIT_PRICE": 50,
      "AMOUNT_AED": 500,
    },
    {
      "id": 7,
      "DESCRIPTION": "Creative Development - 3 x 30 sec Video & Photography",
      "UNITS": 5,
      "UNIT_PRICE": 50,
      "AMOUNT_AED": 500,
    },
    {
      "id": 8,
      "DESCRIPTION": "Creative Development - 3 x 30 sec Video & Photography",
      "UNITS": 5,
      "UNIT_PRICE": 50,
      "AMOUNT_AED": 500,
    },
    {
      "id": 9,
      "DESCRIPTION": "Creative Development - 3 x 30 sec Video & Photography",
      "UNITS": 5,
      "UNIT_PRICE": 50,
      "AMOUNT_AED": 500,
    },
    {
      "id": 10,
      "DESCRIPTION": "PCreative Development - 3 x 30 sec Video & Photography",
      "UNITS": 5,
      "UNIT_PRICE": 50,
      "AMOUNT_AED": 500,
    },
    {
      "id": 11,
      "DESCRIPTION": "PCreative Development - 3 x 30 sec Video & Photography",
      "UNITS": 5,
      "UNIT_PRICE": 50,
      "AMOUNT_AED": 500,
    },
    {
      "id": 12,
      "DESCRIPTION": "PCreative Development - 3 x 30 sec Video & Photography",
      "UNITS": 5,
      "UNIT_PRICE": 50,
      "AMOUNT_AED": 500,
    },
    {
      "id": 13,
      "DESCRIPTION": "PCreative Development - 3 x 30 sec Video & Photography",
      "UNITS": 5,
      "UNIT_PRICE": 50,
      "AMOUNT_AED": 500,
    },
    {
      "id": 14,
      "DESCRIPTION": "PCreative Development - 3 x 30 sec Video & Photography",
      "UNITS": 5,
      "UNIT_PRICE": 50,
      "AMOUNT_AED": 500,
    },
    {
      "id": 15,
      "DESCRIPTION": "PCreative Development - 3 x 30 sec Video & Photography",
      "UNITS": 5,
      "UNIT_PRICE": 50,
      "AMOUNT_AED": 500,
    },
  ];